server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Yogesh-59/Hotel_Management_System.git  # Ensure repo is accessible
          default-label: main  # Make sure this is the correct branch name
          clone-on-start: true  # Optional, ensures a fresh clone at startup

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all monitoring endpoints
