server:
  port: 8080

spring:
  application:
    name: gateway

  config:
    import: "optional:configserver:http://localhost:8888"

  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**

        - id: reservation
          uri: lb://reservation
          predicates:
            - Path=/api/reservations/**

        - id: guest-service
          uri: lb://guest-service
          predicates:
            - Path=/guest/**

        - id: payment-gateway
          uri: lb://payment-gateway
          predicates:
            - Path=/api/payments/**

        - id: staff-service
          uri: lb://staff-service
          predicates:
            - Path=/staff/**

        - id: rate-service
          uri: lb://rate-service
          predicates:
            - Path=/rates/**

        - id: room-service
          uri: lb://room-service
          predicates:
            - Path=/rooms/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
